AWSTemplateFormatVersion: 2010-09-09
Description: Template for LLM Code Reviewer.

Parameters:
  Enviroment:
    Type: String
    Description: The deployment stage name.
    AllowedValues:
      - Prd
      - Stg
      - Dev

  SystemName:
    Type: String
    Description: The system name of the stack.
    Default: llm-code-reviewer

  ImageUri:
    Type: String
    Description: The ECR image URI for the Lambda function's container. e.g.,
      {AccountId}.dkr.ecr.ap-northeast-1.amazonaws.com/your-repo-name:latest

  DomainName:
    Type: String
    Description: Your registered domain name (e.g., example.com).

  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: The Route 53 Hosted Zone ID for your domain.

  FromMailAddress:
    Type: String
    Description: '通知用メールアドレス'

  BedrockModelId:
    Type: String
    Description: The ID of the Amazon Bedrock model to be used for code review.
    Default: anthropic.claude-3-haiku-20240307-v1:0

  BedrockMaxTokens:
    Type: Number
    Description: The maximum number of tokens that the Bedrock model will generate
      in the response.
    Default: 1000

  BedrockTemperature:
    Type: Number
    Description: Controls the randomness of the text generated by the Bedrock model
      (0.0-1.0). Lower values result in more deterministic output, higher values
      in more diverse output.
    Default: 0.5

  BedrockTopP:
    Type: Number
    Description: The Top-P sampling value for the Bedrock model (0.0-1.0). Lower
      values focus on more probable words.
    Default: 0.9

Outputs:
  ApiEndpoint:
    Description: The invoke URL for the API Gateway stage.
    Value: !Sub https://${ApiGatewayBaseStack.Outputs.RestApiId}.execute-api.${AWS::Region}.amazonaws.com/${LLMCodeReviewerApiStage}
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndpoint

Resources:
  # --- サービス共通 - APIデプロイメント ---
  LLMCodeReviewerApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - CodeReviewServiceStack
      - UsageKeyServiceStack
    Properties:
      RestApiId: !GetAtt ApiGatewayBaseStack.Outputs.RestApiId

  # --- サービス共通 - APIステージ ---
  LLMCodeReviewerApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref LLMCodeReviewerApiDeployment
      RestApiId: !GetAtt ApiGatewayBaseStack.Outputs.RestApiId
      StageName: !Ref Enviroment

  # カスタムドメイン名
  LLMCodeReviewerApiGatewayDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref DomainName
      RegionalCertificateArn: !GetAtt CoreInfraStack.Outputs.CertificateArn
      EndpointConfiguration:
        Types: [REGIONAL]

  # ベースパスマッピング
  LLMCodeReviewerApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref LLMCodeReviewerApiGatewayDomainName
      RestApiId: !GetAtt ApiGatewayBaseStack.Outputs.RestApiId
      Stage: !Ref LLMCodeReviewerApiStage

  # Route 53 レコードセット
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref LLMCodeReviewerApiGatewayDomainName
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt LLMCodeReviewerApiGatewayDomainName.RegionalHostedZoneId
        DNSName: !GetAtt LLMCodeReviewerApiGatewayDomainName.RegionalDomainName

  # --- コードレビューサービス - コードレビューAPI用 使用量プラン ---
  CodeReviewUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      Description: CodeReview API Usage Plan
      ApiStages:
        - ApiId: !GetAtt ApiGatewayBaseStack.Outputs.RestApiId
          Stage: !Ref LLMCodeReviewerApiStage
      Quota:
        Limit: 10
        Period: DAY

  # --- 利用キーサービス - 使用量プランID (SSM Parameter) ---
  UsagePlanIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SystemName}/${Enviroment}/usagekey/apigateway/UsagePlanId
      Type: String
      Value: !Ref CodeReviewUsagePlan

  # --------------------------------------------------------------------------
  #  Nested Stacks
  # --------------------------------------------------------------------------

  CoreInfraStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./core-infra.yml
      Parameters:
        HostedZoneId: !Ref HostedZoneId
        DomainName: !Ref DomainName

  ApiGatewayBaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./api-gateway-base.yml

  UsageKeyServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./usage-key-service.yml
      Parameters:
        SystemName: !Ref SystemName
        Enviroment: !Ref Enviroment
        ImageUri: !Ref ImageUri
        RestApiId: !GetAtt ApiGatewayBaseStack.Outputs.RestApiId
        RootResourceId: !GetAtt ApiGatewayBaseStack.Outputs.RootResourceId
        UsageKeyTableName: !GetAtt CoreInfraStack.Outputs.UsageKeyTableName
        AutomationUsageKeyApprovalNotifyTopicArn: !GetAtt CoreInfraStack.Outputs.AutomationUsageKeyApprovalNotifyTopicArn
        FromMailAddress: !Ref FromMailAddress

  CodeReviewServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./code-review-service.yml
      Parameters:
        SystemName: !Ref SystemName
        Enviroment: !Ref Enviroment
        ImageUri: !Ref ImageUri
        BedrockModelId: !Ref BedrockModelId
        BedrockMaxTokens: !Ref BedrockMaxTokens
        BedrockTemperature: !Ref BedrockTemperature
        BedrockTopP: !Ref BedrockTopP
        RestApiId: !GetAtt ApiGatewayBaseStack.Outputs.RestApiId
        RootResourceId: !GetAtt ApiGatewayBaseStack.Outputs.RootResourceId