name: Backend Application CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test/**'

  workflow_dispatch:

jobs:
  lint_and_format:
    name: Lin and Format check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with: ./src


  unittest:
    needs: lint_and_format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        env:
          PYTHONPATH: src
        run: python -m unittest discover --top-level-directory . --start-directory test --verbose
